### PR TITLE
vendor: clean up unused imports

### PR DESCRIPTION
**Pull request by LiliC**
With the new release of dep, it is easy to purge on each dep ensure.
This commit also adds the necessary configs to the Gopkg.lock file to be
able to do that.

### CODE REVIEW

**Comment by krnowak** [comment]
Is there anything that checks that dep is 0.4 or newer? I wonder how dep will behave if somebody uses an older version.

Otherwise LFAD if green.

**Comment by LiliC** [comment]
@krnowak good point, will add it to the README. That we require dep version onwards from `0.4`.

**Comment by LiliC** [comment]
@krnowak done. 👍

**Comment by asymmetric** [comment]
FYI the [`[solve-meta]`](https://golang.github.io/dep/docs/Gopkg.lock.html) section of the `Gopkg.lock` has versioning information. In our case, it contains [this](https://github.com/kinvolk/habitat-operator/blob/dcba88e4663bc67f2f1715344679a35ca7510c22/Gopkg.lock#L427-L432).

**Pull request merged**
