### PR TITLE
Use numeric dependency versions for clarity

### PR DESCRIPTION
**Pull request by asymmetric**
Revisions are opaque, versions make it clear which version we're
running.

Signed-off-by: Lorenzo Manacorda <lorenzo@kinvolk.io>

### CODE REVIEW

**Comment by LiliC** [comment]
I would also bump to newer version of client-go, etc., since I changed this new releases were made.

**Comment by asymmetric** [comment]
[v6](https://github.com/kubernetes/client-go/releases/tag/v6.0.0) is the latest stable AFAICT.

**Comment by LiliC** [comment]
@asymmetric you can now take the k8s tags as well, the auto merging into that repo was fixed IIRC.

**Comment by asymmetric** [comment]
I read [this](https://github.com/kubernetes/client-go#kubernetes-tags) and I have no idea what it means.

**Comment by LiliC** [comment]
@asymmetric all of the client/lib repos come from the k8s main repos staging area. They have a tool that builds and "copies" the code over to the separate client/lib repos. There was an article published recently, you can have a look http://blog.kubernetes.io/2018/01/introducing-client-go-version-6.html

**Comment by asymmetric** [comment]
Cool, thanks for the link. I still don't understand those `kubernetes-` tags, but I think that anyway upgrading can be done in another PR, if necessary.

**Comment by asymmetric** [comment]
@LiliC In regards to updating to newer versions, I'd like to keep this PR as is, so that it's clear that we're not changing anything, just using a clearer naming.

I'll open a separate PR where I bump the minor versions.

**Comment by krnowak** [comment]
LFAD if an issue or a PR about upgrading is filed too. Or is #173 about it too?

**Comment by asymmetric** [comment]
I've created #175 for that.

**Pull request merged**
